config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  namespace :backoffice do
    resources :places

    root to: 'pages#dashboard'
  end

  resources :places, only: [:index, :show]

  get 'pages/dashboard', to: 'pages#dashboard', as: :dashboard
  root to: 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!
  # before_action :authenticate_admin!

  helper_method :output_debug

  def after_sign_in_path_for(resource)
    if current_admin.present?
      backoffice_root_path
    else
      dashboard_path
    end
  end

  # Public helper methods
  #### Simplify output for debug variables in rails console
  def output_debug(params)
    Rails.logger.debug("\n\n\n\n------------------------------------------------\n")
    Rails.logger.debug(params.inspect)
    Rails.logger.debug("\n------------------------------------------------\n\n\n\n")
  end

  protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  # en
end

app/controllers/backoffice/pages_controller.rb
class Backoffice::PagesController < BackofficeController
  def dashboard
  end
end

app/controllers/backoffice/places_controller.rb
class Backoffice::PlacesController < BackofficeController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  #before_action :set_form_url, only: [:new, :edit]

  # GET /places
  def index
    @places = Place.all
  end

  # GET /places/1
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @resource_path = backoffice_places_path
  end

  # GET /places/1/edit
  def edit
    @resource_path = backoffice_place_path(@place)
  end

  # POST /places
  def create
    @place = Place.new(place_params)

    if @place.save
      redirect_to @place, notice: 'Place was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /places/1
  def update
    if @place.update(place_params)
      redirect_to @place, notice: 'Place was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /places/1
  def destroy
    @place.destroy
    redirect_to places_url, notice: 'Place was successfully destroyed.'
  end

  private
    def set_form_url
      if @place.try(:id).try(:nil?)
        @resource_path = backoffice_places_path
      else
        @resource_path = backoffice_place_path(@place)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:description)
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  #  protect_from_forgery prepend: true, with: :exception
  before_action :authenticate_admin!

  layout "backoffice"
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :dashboard

  def index
  end

  def dashboard
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: :show

  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  def index
    @places = Place.all
  end

  # GET /places/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/backoffice/pages/dashboard.html.erb
<h1>ESTO SE VE SOLAMENTE ADMINSITRADOR</h1>

<blockquote>
  # app/controllers/backoffice/pages_controller.rb
  # pages#dashboard
</blockquote>

app/views/backoffice/places/_form.html.erb
<%= simple_form_for(@place, url: @resource_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/backoffice/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', backoffice_place_path(@place) %> |
<%= link_to 'Back', backoffice_places_path %>

app/views/backoffice/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.description %></td>
        <td><%= link_to 'Show', backoffice_place_path(place) %></td>
        <td><%= link_to 'Edit', edit_backoffice_place_path(place) %></td>
        <td><%= link_to 'Destroy', backoffice_place_path(place), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_backoffice_place_path %>

app/views/backoffice/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', backoffice_places_path %>

app/views/backoffice/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<%= link_to 'Edit', edit_backoffice_place_path(@place) %> |
<%= link_to 'Back', backoffice_places_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseTwoModelsDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if user_signed_in? %>
        <%= link_to "Logout USer", destroy_user_session_path, class: "btn btn-sm btn-danger" %>
      <% else %>
        <%= link_to "Login USer", new_user_session_path, class: "btn btn-sm btn-secondary" %>
      <% end %>

      <% if admin_signed_in? %>
        <%= link_to "Logout Admin", destroy_admin_session_path, class: "btn btn-sm btn-danger" %>
      <% else %>
        <%= link_to "Login Admin", new_admin_session_path, class: "btn btn-sm btn-secondary" %>
      <% end %>

      <br>
      <br>
      <br>
      <br>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BACKOFFICE - SOLO ADMINISTRADORES</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= link_to 'Ver lugares', backoffice_places_path, class: "btn btn-sm btn-dark" if admin_signed_in? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>ESTA PAGINA ES ACCESIBLE SOLO POR USUARIOS</h1>


<blockquote>
  # app/controllers/pages_controller.rb
  # pages#dashboard
</blockquote>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.description %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>